In [1]:
import numpy as np

**分箱实现**：

1. 借助函数：`np.linspace` 和 `np.digitize`
2. 借助类：`from sklearn.preprocessing import KBinsDiscretizer`

In [8]:
X = 3 * np.random.random((10, 1))
X

array([[0.21892615],
       [1.66444985],
       [0.78253753],
       [2.49826158],
       [1.93018738],
       [2.79310796],
       [1.85204177],
       [2.03719548],
       [2.42122826],
       [0.90486728]])

In [19]:
bins = np.linspace(X.min()-0.01, X.max()+.01, 11)
bins

array([0.20892615, 0.46834433, 0.72776252, 0.9871807 , 1.24659888,
       1.50601706, 1.76543524, 2.02485342, 2.2842716 , 2.54368978,
       2.80310796])

In [20]:
which_bins = np.digitize(X, bins=bins)
which_bins

array([[ 1],
       [ 6],
       [ 3],
       [ 9],
       [ 7],
       [10],
       [ 7],
       [ 8],
       [ 9],
       [ 3]], dtype=int64)

In [24]:
from sklearn.preprocessing import KBinsDiscretizer
kb = KBinsDiscretizer(n_bins=10, strategy='uniform')
kb.fit_transform(X).toarray()

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
kb = KBinsDiscretizer(n_bins=10, strategy='uniform', encode='onehot-dense')
kb.fit_transform(X)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.]])